safe: true
lsi: false

root_url: http://ashishsingh21798.github.io
author:
  name: ashishsingh21798.github.io
title: Ashish Singh- Creativity freak!
permalink: /blog/:year/:month/:title/
highlighter: rouge

lab_projects:
- name: "Project Pytho"
  link: "https://github.com/ashishsingh21798/pytho"
  desc: "My peronal Digital Asistance"
- name: "Store data in structure-C language"
  link: "https://github.com/ashishsingh21798/Data-store-in-Structure-C"
  desc: "Store data using C language"
- name: "Multiple Data Compresion and Decompression (MDC)"
  link: "https://github.com/ashishsingh21798/MDC-multiple-data-compression-"
  desc: "Uses basic C programming concepts and bit manupulation for data compression and decompression. Will do the MDC in iterative way i.e, Compressing the file in iterative way..as much as possible."
